version: '3.1'

services:
  nnpia-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db_dev

  nnpia-adminer:
    image: adminer
    ports:
      - 8001:8080